use bytes::{Buf, BytesMut};

use crate::error::ProtocolError;
use crate::messages::{ClientMessage, ServerMessage};

/// Maximum TCP message size: 64 KiB.
pub const MAX_MSG_SIZE: u32 = 65_536;

/// Largest encrypted blob the server will relay: 60 KiB.
///
/// Nothing a client hands the server to pass on comes back out the same size.
/// The relay re-wraps every blob with the sender's user id, the name they go
/// by there (up to 32 bytes) and a timestamp, so a blob that only just fits
/// through `try_decode_frame` on the way in is an unframeable message on the
/// way out. There is no way to deliver that: every recipient's decoder would
/// error on the length prefix and their client would drop the connection, so
/// one message would disconnect everybody in the channel at once. The 4 KiB
/// of headroom is what the re-wrapping costs, with room left over.
pub const MAX_RELAY_CIPHERTEXT: usize = 60 * 1024;

/// How many control messages a second one connection may send.
///
/// Read from both ends: the server charges a token per frame before it decodes
/// one, and a client paces itself just under it. Without the second half the
/// first half is a trap — a client that means no harm can exceed it on a busy
/// connect (a prekey bundle per person, a sender key per person per channel),
/// and what it loses is silent: a key that never arrives is a member who
/// cannot read the channel, with nothing on screen to say so.
pub const CONTROL_MSGS_PER_SEC: u32 = 50;

/// Current protocol version.
/// v2: Base protocol with screen share
/// v3: E2E encryption (Signal Protocol + AES-256-GCM media)
/// v4: media keys generated by clients and exchanged over Signal sessions
///     (server-issued ChannelMediaKey removed; DistributeMediaKey carries message_type)
/// v5: everything over one QUIC connection — udp_token removed from media
///     headers and from Authenticated; VideoLossReport/VideoLossReported added
/// v6: proximity chat — ChannelInfo.proximity, CreateChannel.proximity,
///     SetChannelProximity, encrypted Position media packet (0x06)
/// v7: channel options — ChannelInfo.hidden/anonymous/screen_share/hide_members,
///     CreateChannel.anonymous, SetChannelOptions
/// v8: routed channels — ChannelInfo.routed, SetChannelOptions.routed,
///     SetAudioFilter (a client naming who it wants to hear)
/// v9: text channels — ChannelInfo.text/auto_join, CreateChannel.text,
///     LeaveChannel, SendEncryptedChannelMessage.channel_id;
///     history sharing — UserInfo.shares_history, SetHistorySharing,
///     UserHistorySharing;
///     media nonces — encrypted voice/video/screen-audio headers carry a
///     sender-chosen stream_id, so two members under one channel key cannot
///     be given the same nonce by the server;
///     message destruction timers — ChannelInfo.message_ttl_secs,
///     SetChannelOptions.message_ttl_secs, and a `ttl` inside the message
///     envelope, which the server never sees
pub const PROTOCOL_VERSION: u32 = 9;

/// Application version, read from Cargo.toml at compile time.
/// Single source of truth: workspace root `Cargo.toml` `[workspace.package] version`.
pub const APP_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Encode a `ClientMessage` into a length-prefixed byte buffer for TCP transmission.
pub fn encode_client_msg(msg: &ClientMessage) -> Result<Vec<u8>, ProtocolError> {
    let payload = postcard::to_allocvec(msg)?;
    let mut buf = Vec::with_capacity(4 + payload.len());
    buf.extend_from_slice(&(payload.len() as u32).to_be_bytes());
    buf.extend_from_slice(&payload);
    Ok(buf)
}

/// Decode a `ClientMessage` from a postcard-encoded payload (without length prefix).
pub fn decode_client_msg(payload: &[u8]) -> Result<ClientMessage, ProtocolError> {
    Ok(postcard::from_bytes(payload)?)
}

/// Encode a `ServerMessage` into a length-prefixed byte buffer for TCP transmission.
pub fn encode_server_msg(msg: &ServerMessage) -> Result<Vec<u8>, ProtocolError> {
    let payload = postcard::to_allocvec(msg)?;
    // The backstop under `MAX_RELAY_CIPHERTEXT`, which is the policy. A frame
    // this long cannot be read by anybody — the receiver rejects the length
    // prefix and drops the connection — so it must never reach a socket, no
    // matter which relay path built it. Every caller sends through `send_msg`
    // and discards its `Result`, so this costs one dropped message where the
    // alternative costs a session.
    if payload.len() > MAX_MSG_SIZE as usize {
        return Err(ProtocolError::MessageTooLarge(payload.len()));
    }
    let mut buf = Vec::with_capacity(4 + payload.len());
    buf.extend_from_slice(&(payload.len() as u32).to_be_bytes());
    buf.extend_from_slice(&payload);
    Ok(buf)
}

/// Decode a `ServerMessage` from a postcard-encoded payload (without length prefix).
pub fn decode_server_msg(payload: &[u8]) -> Result<ServerMessage, ProtocolError> {
    Ok(postcard::from_bytes(payload)?)
}

/// Attempt to extract one complete length-prefixed frame from a byte buffer.
///
/// Returns `Ok(Some(payload))` if a complete message is available,
/// `Ok(None)` if more data is needed, or `Err` if the message is too large.
///
/// Advances the buffer past the consumed frame.
pub fn try_decode_frame(buf: &mut BytesMut) -> Result<Option<Vec<u8>>, ProtocolError> {
    if buf.len() < 4 {
        return Ok(None);
    }

    let length = u32::from_be_bytes([buf[0], buf[1], buf[2], buf[3]]) as usize;

    if length > MAX_MSG_SIZE as usize {
        return Err(ProtocolError::MessageTooLarge(length));
    }

    if buf.len() < 4 + length {
        return Ok(None);
    }

    buf.advance(4);
    let payload = buf.split_to(length).to_vec();
    Ok(Some(payload))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn roundtrip_client_message() {
        let msg = ClientMessage::Authenticate {
            username: "alice".into(),
            protocol_version: PROTOCOL_VERSION,
            app_version: APP_VERSION.to_string(),
            identity_key: None,
            prekey_bundle: None,
        };
        let encoded = encode_client_msg(&msg).unwrap();
        // Skip the 4-byte length prefix
        let decoded = decode_client_msg(&encoded[4..]).unwrap();
        match decoded {
            ClientMessage::Authenticate {
                username,
                protocol_version,
                ..
            } => {
                assert_eq!(username, "alice");
                assert_eq!(protocol_version, PROTOCOL_VERSION);
            }
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn roundtrip_server_message() {
        let msg = ServerMessage::Authenticated {
            user_id: 1,
            session_id: 42,
        };
        let encoded = encode_server_msg(&msg).unwrap();
        let decoded = decode_server_msg(&encoded[4..]).unwrap();
        match decoded {
            ServerMessage::Authenticated {
                user_id,
                session_id,
            } => {
                assert_eq!(user_id, 1);
                assert_eq!(session_id, 42);
            }
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn roundtrip_video_loss_messages() {
        let msg = ClientMessage::VideoLossReport {
            sharer_user_id: 7,
            frames_dropped: 3,
            frames_received: 40,
        };
        let encoded = encode_client_msg(&msg).unwrap();
        let decoded = decode_client_msg(&encoded[4..]).unwrap();
        assert!(matches!(
            decoded,
            ClientMessage::VideoLossReport { sharer_user_id: 7, frames_dropped: 3, frames_received: 40 }
        ));

        let msg = ServerMessage::VideoLossReported {
            viewer_user_id: 9,
            frames_dropped: 3,
            frames_received: 40,
        };
        let encoded = encode_server_msg(&msg).unwrap();
        let decoded = decode_server_msg(&encoded[4..]).unwrap();
        assert!(matches!(
            decoded,
            ServerMessage::VideoLossReported { viewer_user_id: 9, frames_dropped: 3, frames_received: 40 }
        ));
    }

    #[test]
    fn frame_decoding() {
        let msg = ClientMessage::Ping { timestamp: 12345 };
        let encoded = encode_client_msg(&msg).unwrap();

        let mut buf = BytesMut::new();

        // Partial data — should return None
        buf.extend_from_slice(&encoded[..3]);
        assert!(try_decode_frame(&mut buf).unwrap().is_none());

        // Complete data
        buf.extend_from_slice(&encoded[3..]);
        let payload = try_decode_frame(&mut buf).unwrap().unwrap();
        let decoded = decode_client_msg(&payload).unwrap();
        match decoded {
            ClientMessage::Ping { timestamp } => assert_eq!(timestamp, 12345),
            _ => panic!("wrong variant"),
        }

        // Buffer should be empty now
        assert!(buf.is_empty());
    }

    #[test]
    fn roundtrip_join_channel() {
        let msg = ClientMessage::JoinChannel {
            channel_id: 42,
            password: Some("secret".into()),
        };
        let encoded = encode_client_msg(&msg).unwrap();
        let decoded = decode_client_msg(&encoded[4..]).unwrap();
        match decoded {
            ClientMessage::JoinChannel { channel_id, password } => {
                assert_eq!(channel_id, 42);
                assert_eq!(password, Some("secret".into()));
            }
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn roundtrip_create_channel() {
        let msg = ClientMessage::CreateChannel {
            name: "TestRoom".into(),
            password: None,
            proximity: crate::types::ProximityMode::ThreeD,
            anonymous: true,
            text: false,
        };
        let encoded = encode_client_msg(&msg).unwrap();
        let decoded = decode_client_msg(&encoded[4..]).unwrap();
        match decoded {
            ClientMessage::CreateChannel {
                name,
                password,
                proximity,
                anonymous,
                text,
            } => {
                assert_eq!(name, "TestRoom");
                assert!(password.is_none());
                assert_eq!(proximity, crate::types::ProximityMode::ThreeD);
                assert!(anonymous);
                assert!(!text);
            }
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn roundtrip_set_audio_filter() {
        // `None` and an empty list are different answers — "everybody" and
        // "nobody" — and postcard has to carry that difference intact.
        for allow in [None, Some(vec![]), Some(vec![7, 42])] {
            let msg = ClientMessage::SetAudioFilter {
                allow: allow.clone(),
            };
            let encoded = encode_client_msg(&msg).unwrap();
            match decode_client_msg(&encoded[4..]).unwrap() {
                ClientMessage::SetAudioFilter { allow: back } => assert_eq!(back, allow),
                _ => panic!("wrong variant"),
            }
        }
    }

    #[test]
    fn roundtrip_set_channel_options() {
        // None leaves an option alone; the server must be able to tell that
        // apart from "set it to false".
        let msg = ClientMessage::SetChannelOptions {
            channel_id: 3,
            hidden: Some(true),
            anonymous: None,
            screen_share: Some(false),
            hide_members: None,
            routed: Some(true),
            message_ttl_secs: Some(3600),
        };
        let encoded = encode_client_msg(&msg).unwrap();
        match decode_client_msg(&encoded[4..]).unwrap() {
            ClientMessage::SetChannelOptions {
                channel_id,
                hidden,
                anonymous,
                screen_share,
                hide_members,
                routed,
                message_ttl_secs,
            } => {
                assert_eq!(channel_id, 3);
                assert_eq!(hidden, Some(true));
                assert_eq!(anonymous, None);
                assert_eq!(screen_share, Some(false));
                assert_eq!(hide_members, None);
                assert_eq!(routed, Some(true));
                assert_eq!(message_ttl_secs, Some(3600));
            }
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn roundtrip_disconnect() {
        let msg = ClientMessage::Disconnect;
        let encoded = encode_client_msg(&msg).unwrap();
        let decoded = decode_client_msg(&encoded[4..]).unwrap();
        assert!(matches!(decoded, ClientMessage::Disconnect));
    }

    #[test]
    fn roundtrip_screen_share_messages() {
        let msg = ClientMessage::StartScreenShare {
            source: "screen:0".into(),
            resolution: 1080,
            codec: crate::types::VideoCodec::Vp9,
        };
        let encoded = encode_client_msg(&msg).unwrap();
        let decoded = decode_client_msg(&encoded[4..]).unwrap();
        match decoded {
            ClientMessage::StartScreenShare { source, resolution, codec } => {
                assert_eq!(source, "screen:0");
                assert_eq!(resolution, 1080);
                assert_eq!(codec, crate::types::VideoCodec::Vp9);
            }
            _ => panic!("wrong variant"),
        }

        let msg = ClientMessage::WatchScreenShare { sharer_user_id: 7 };
        let encoded = encode_client_msg(&msg).unwrap();
        let decoded = decode_client_msg(&encoded[4..]).unwrap();
        assert!(matches!(decoded, ClientMessage::WatchScreenShare { sharer_user_id: 7 }));

        // The viewer learns the codec here, not from ScreenShareStarted
        let msg = ServerMessage::WatchingScreenShare {
            sharer_user_id: 7,
            codec: crate::types::VideoCodec::H265,
        };
        let encoded = encode_server_msg(&msg).unwrap();
        let decoded = decode_server_msg(&encoded[4..]).unwrap();
        match decoded {
            ServerMessage::WatchingScreenShare { sharer_user_id, codec } => {
                assert_eq!(sharer_user_id, 7);
                assert_eq!(codec, crate::types::VideoCodec::H265);
            }
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn roundtrip_encrypted_chat_messages() {
        let msg = ServerMessage::EncryptedChannelChatMessage {
            channel_id: 1,
            user_id: 5,
            username: "alice".into(),
            ciphertext: vec![0xDE, 0xAD, 0xBE, 0xEF],
            timestamp: 999,
        };
        let encoded = encode_server_msg(&msg).unwrap();
        let decoded = decode_server_msg(&encoded[4..]).unwrap();
        match decoded {
            ServerMessage::EncryptedChannelChatMessage { channel_id, user_id, username, ciphertext, timestamp } => {
                assert_eq!(channel_id, 1);
                assert_eq!(user_id, 5);
                assert_eq!(username, "alice");
                assert_eq!(ciphertext, vec![0xDE, 0xAD, 0xBE, 0xEF]);
                assert_eq!(timestamp, 999);
            }
            _ => panic!("wrong variant"),
        }

        let msg = ServerMessage::EncryptedDirectChatMessage {
            from_user_id: 1,
            from_username: "bob".into(),
            to_user_id: 2,
            ciphertext: vec![0xCA, 0xFE],
            message_type: 2,
            timestamp: 1000,
        };
        let encoded = encode_server_msg(&msg).unwrap();
        let decoded = decode_server_msg(&encoded[4..]).unwrap();
        assert!(matches!(decoded, ServerMessage::EncryptedDirectChatMessage { .. }));
    }

    #[test]
    fn frame_message_too_large() {
        let mut buf = BytesMut::new();
        let bad_len = (MAX_MSG_SIZE + 1).to_be_bytes();
        buf.extend_from_slice(&bad_len);
        buf.extend_from_slice(&[0u8; 100]);
        let result = try_decode_frame(&mut buf);
        assert!(matches!(result, Err(ProtocolError::MessageTooLarge(_))));
    }

    /// The two ends of the size chain have to meet: a blob at
    /// `MAX_RELAY_CIPHERTEXT` must still frame after the relay re-wraps it
    /// with a full-length name and a timestamp, and anything that does not
    /// frame must be refused here rather than written to a socket where the
    /// recipient's decoder would kill the connection over it.
    #[test]
    fn a_server_message_too_large_to_frame_is_refused() {
        let wrapped = |len: usize| ServerMessage::EncryptedChannelChatMessage {
            channel_id: u32::MAX,
            user_id: u32::MAX,
            username: "x".repeat(32),
            ciphertext: vec![0u8; len],
            timestamp: u64::MAX,
        };

        let encoded = encode_server_msg(&wrapped(MAX_RELAY_CIPHERTEXT)).unwrap();
        assert!(
            encoded.len() <= MAX_MSG_SIZE as usize,
            "a relayable blob came back out as an unframeable {} byte message",
            encoded.len()
        );

        let err = encode_server_msg(&wrapped(MAX_MSG_SIZE as usize));
        assert!(matches!(err, Err(ProtocolError::MessageTooLarge(_))));
    }

    #[test]
    fn frame_partial_length() {
        let mut buf = BytesMut::new();
        buf.extend_from_slice(&[0, 0]); // only 2 bytes, need 4
        assert!(try_decode_frame(&mut buf).unwrap().is_none());
    }

    #[test]
    fn frame_multiple_messages() {
        let msg1 = ClientMessage::Ping { timestamp: 1 };
        let msg2 = ClientMessage::Ping { timestamp: 2 };
        let enc1 = encode_client_msg(&msg1).unwrap();
        let enc2 = encode_client_msg(&msg2).unwrap();

        let mut buf = BytesMut::new();
        buf.extend_from_slice(&enc1);
        buf.extend_from_slice(&enc2);

        let payload1 = try_decode_frame(&mut buf).unwrap().unwrap();
        let payload2 = try_decode_frame(&mut buf).unwrap().unwrap();
        match decode_client_msg(&payload1).unwrap() {
            ClientMessage::Ping { timestamp } => assert_eq!(timestamp, 1),
            _ => panic!("wrong variant"),
        }
        match decode_client_msg(&payload2).unwrap() {
            ClientMessage::Ping { timestamp } => assert_eq!(timestamp, 2),
            _ => panic!("wrong variant"),
        }
        assert!(buf.is_empty());
    }
}
